(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&r(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();document.querySelector(".footer-comment").addEventListener("input",function(){const o=this.cols;this.value.length>o&&(this.value=this.value.substring(0,o-3)+"...")});document.getElementById("email").addEventListener("input",function(){const o=this,t=document.getElementById("email-validation");o.checkValidity()?(o.classList.remove("error"),o.classList.add("success"),t.textContent="Success!",t.classList.remove("error"),t.classList.add("success")):(o.classList.remove("success"),o.classList.add("error"),t.textContent="Invalid email, try again",t.classList.remove("success"),t.classList.add("error"))});document.querySelector(".form-btn").addEventListener("click",function(o){o.preventDefault();const t=document.getElementById("email").value,n=document.getElementById("comment").value;fetch("https://portfolio-js.b.goit.study/api/requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:t,comment:n})}).then(e=>{if(!e.ok)throw new Error("Server error");return e.json()}).then(e=>{document.querySelector(".footer-form").reset(),i(e.title,e.message)}).catch(e=>{d("Error","Something went wrong. Please check your input and try again.")})});function i(o,t){const n=document.createElement("div");n.classList.add("modal"),n.innerHTML=`
        <div class="modal-content">
            <button class="modal-close">X</button>
            <h3>${o}</h3>
            <p>${t}</p>
        </div>
    `,document.body.appendChild(n),n.querySelector(".modal-close").addEventListener("click",function(){document.body.removeChild(n)})}function d(o,t){const n=document.createElement("div");n.classList.add("toast"),n.innerHTML=`
        <strong>${o}</strong>
        <p>${t}</p>
    `,document.body.appendChild(n),setTimeout(()=>{document.body.removeChild(n)},3e3)}
//# sourceMappingURL=commonHelpers.js.map
